server:
  port: 8086
spring:
  application:
    name: sc-order
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    consul:
      host: 192.168.99.103
      port: 8500
      discovery:
        enabled: true
        instance-id: sc-order
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://www.liaowei.net.cn:3306/sc-db?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
swagger:
  enabled: true
  base-package: cn.net.liaowei.sc.order
  title: "订单服务"
  version: v0.0.1
  host: "{{host}}:8086"

